helm:
  parameters:
  - name: image.repository
    value: 905418475780.dkr.ecr.ap-south-1.amazonaws.com/prod/api
    forcestring: false
  - name: image.tag
    value: 5-api-M-77bcabb98d1bb0549602596edd426066234bfa86
    forcestring: true
  - name: replicaCount
    value: "1"
    forcestring: false
  - name: image.name
    value: 905418475780.dkr.ecr.ap-south-1.amazonaws.com/prod/api
    forcestring: true
