helm:
  parameters:
  - name: image.repository
    value: 905418475780.dkr.ecr.ap-south-1.amazonaws.com/dev/api
    forcestring: false
  - name: image.tag
    value: 2-api-M-3956b043a60b9ac5b57a5bce3bf749a9f9d1f105
    forcestring: true
  - name: replicaCount
    value: "1"
    forcestring: false
  - name: image.name
    value: 905418475780.dkr.ecr.ap-south-1.amazonaws.com/dev/api
    forcestring: true
