helm:
  parameters:
  - name: image.repository
    value: 905418475780.dkr.ecr.ap-south-1.amazonaws.com/prod/api
    forcestring: false
  - name: image.tag
    value: 6-api-M-b97e16d4f7ae44a373654e6f3fa6e7cb3a37189b
    forcestring: true
  - name: replicaCount
    value: "1"
    forcestring: false
  - name: image.name
    value: 905418475780.dkr.ecr.ap-south-1.amazonaws.com/prod/api
    forcestring: true
