helm:
  parameters:
  - name: image.repository
    value: 905418475780.dkr.ecr.ap-south-1.amazonaws.com/prod/api
    forcestring: false
  - name: image.tag
    value: 4-api-M-1da204c658642248090987d515a55c6e4be4e299
    forcestring: true
  - name: replicaCount
    value: "1"
    forcestring: false
  - name: image.name
    value: 905418475780.dkr.ecr.ap-south-1.amazonaws.com/prod/api
    forcestring: true
