replicaCount: 1
image:
  repository: ${actions.build.api.outputs.deploymentImageId}
  pullPolicy: IfNotPresent
  tag: latest

env:
  PGHOSTNAME: postgres
  PGDATABASE: postgres
  PGUSER: postgres
  PGPASSWORD: postgres

resources:
  limits:
    cpu: "1"
    memory: 1Gi
  requests:
    cpu: 10m
    memory: 90Mi

livenessProbe:
  initialDelaySeconds: 90
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 30
  timeoutSeconds: 3

readinessProbe:
  initialDelaySeconds: 2
  periodSeconds: 1
  successThreshold: 2
  failureThreshold: 90
  timeoutSeconds: 3

service:
  port: 80
  targetPort: 8080
  type: LoadBalancer
