helm:
  parameters:
  - name: image.repository
    value: 905418475780.dkr.ecr.ap-south-1.amazonaws.com/prod/web
    forcestring: false
  - name: image.tag
    value: 18-web-M-1851f0b5b4f10f85c653ce9e69b679db237604bd
    forcestring: true
  - name: replicaCount
    value: "1"
    forcestring: false
  - name: image.name
    value: 905418475780.dkr.ecr.ap-south-1.amazonaws.com/prod/web
    forcestring: true
