helm:
  parameters:
  - name: image.repository
    value: 905418475780.dkr.ecr.ap-south-1.amazonaws.com/dev/web
    forcestring: false
  - name: image.tag
    value: 6-web-D-52438fda5e2386e71a70b84740f8efcdcaebfb5f
    forcestring: true
  - name: replicaCount
    value: "1"
    forcestring: false
  - name: image.name
    value: 905418475780.dkr.ecr.ap-south-1.amazonaws.com/dev/web
    forcestring: true
