replicaCount: 1
image:
  repository: ${actions.build.web.outputs.deploymentImageId}
  pullPolicy: IfNotPresent
  tag: latest

env:
  HOSTNAME: "web.${providers.ephemeral-kubernetes.outputs.default-hostname}"
  VUE_APP_USERNAME: ${local.username}

resources:
  limits:
    memory: 300Mi
  requests:
    cpu: 10m
    memory: 90Mi

livenessProbe:
  initialDelaySeconds: 90
  periodSeconds: 5
  successThreshold: 1
  failureThreshold: 3
  timeoutSeconds: 3

readinessProbe:
  initialDelaySeconds: 2
  periodSeconds: 1
  successThreshold: 2
  failureThreshold: 90
  timeoutSeconds: 3

ingress:
  enabled: true
  className: nginx
  host: "web.${providers.ephemeral-kubernetes.outputs.default-hostname}"

service:
  port: 80
  targetPort: 8080
  type: ClusterIP
