replicaCount: 1
image:
  repository: 905418475780.dkr.ecr.ap-south-1.amazonaws.com/dev/web
  pullPolicy: IfNotPresent
  tag: 4-web-D-f163cf5880d504b1f6f51389219d8332cbe60fea

env:
  HOSTNAME: "web-service-host"
  VUE_APP_USERNAME: ${local.username}

resources:
  limits:
    memory: 300Mi
  requests:
    cpu: 10m
    memory: 90Mi

livenessProbe:
  initialDelaySeconds: 90
  periodSeconds: 5
  successThreshold: 1
  failureThreshold: 3
  timeoutSeconds: 3

readinessProbe:
  initialDelaySeconds: 2
  periodSeconds: 1
  successThreshold: 2
  failureThreshold: 90
  timeoutSeconds: 10

service:
  port: 80
  targetPort: 8080
  type: LoadBalancer
