replicaCount: 2
image:
  repository: your-docker-repo/api
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

resources: {}
# Uncomment and configure as needed
# resources:
#   limits:
#     cpu: 500m
#     memory: 512Mi
#   requests:
#     cpu: 250m
#     memory: 256Mi

nodeSelector: {}
tolerations: []
affinity: {}

sync:
  sourcePath: .
  containerPath: /app
  mode: one-way-replica
  overrideCommand: ["/bin/sh", "-c", "ls /app/app.py | entr -r -n python /app/app.py"]
